### ISSUE TITLE
Tree programs

### ISSUE THREAD

**Issue by CrOpid** [CrOpid/Code-Dump-HacktoberFest-2022#13]
Create a folder for tree and add tree related programs

**Comment by ragnarok-02** [comment]
Can you please assign this to me?

**Comment by Aniumbott** [comment]
I would also like to contribute as well.

**Comment by deepanshmittal** [comment]
I would like to contribute to this as well, could you please assign this to me also.

**Comment by CrOpid** [comment]
solved
